PRETRAIN:
  ENABLE: true
  GENERATOR: ContrastiveGenerator
  LOSS: Contrastive
  LOSS_WEIGHTS: [1]
  NUM_CLIPS_PER_VIDEO: 2
  CONTRASTIVE:
    TEMPERATURE: 0.1
    WITH_ONE: true
    MODE: 1
    HEAD_BN: true
    FINAL_BN: false
    SIM_FUNC_POS: linear
    SIM_FUNC_NEG: linear
    POS_OPTIM_TARGET: 1.0
    HEAD_MID_DIM: 1024
    HEAD_OUT_DIM: 128
    INS_MIL: false

TRAIN:
  ENABLE: true
  DATASET:                          # !!@1
  BATCH_SIZE: 10
  LOG_FILE: training_log.log
  EVAL_PERIOD: 0
  NUM_FOLDS: 1
  AUTO_RESUME: true
  CHECKPOINT_PERIOD: 10
  CHECKPOINT_FILE_PATH: ""          # !!@2
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_INFLATE: false
  FINE_TUNE: false
  ONLY_LINEAR: false
TEST:
  ENABLE: false                     # !!@3
  DATASET:                          # !!@3
  BATCH_SIZE: 10
  NUM_SPATIAL_CROPS: 1
  SPATIAL_CROPS: cc
  NUM_ENSEMBLE_VIEWS: 1
  LOG_FILE: val.log
  CHECKPOINT_FILE_PATH: ""
  CHECKPOINT_TYPE: pytorch
  AUTOMATIC_MULTI_SCALE_TEST: false
DATA:
  DATA_ROOT_DIR: 
  ANNO_DIR: 
  NUM_INPUT_FRAMES: 16
  NUM_INPUT_CHANNELS: 3
  SAMPLING_MODE: interval_based
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [168, 224]
  TRAIN_CROP_SIZE: 112
  TEST_SCALE: 224
  TEST_CROP_SIZE: 112
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
  MULTI_LABEL: false
  ENSEMBLE_METHOD: sum
  FPS: 30
  TARGET_FPS: 30
OPTIMIZER:
  BASE_LR: 0.3
  LR_POLICY: cosine
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-6
  WARMUP_EPOCHS: 2
  WARMUP_START_LR: 0.001
  OPTIM_METHOD: lars
  DAMPENING: 0.0
  NESTEROV: true
  BN_LARS_EXCLUDE: false
BN:
  WEIGHT_DECAY: 0.0
  EPS: 1e-3
  SYNC_BN: true
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: false
  ENABLE_MULTI_THREAD_DECODE: true
NUM_GPUS: 8
SHARD_ID: 0
NUM_SHARDS: 1
RANDOM_SEED: 0
OUTPUT_DIR: 
OUTPUT_CFG_FILE: configuration.log
LOG_PERIOD: 10
DIST_BACKEND: nccl
LOG_MODEL_INFO: true
LOG_CONFIG_INFO: true
AUGMENTATION:
  BRIGHTNESS: 0.8
  CONTRAST: 0.8
  SATURATION: 0.8
  HUE: 0.2
  GRAYSCALE: 0.2
  COLOR: 0.8
  CONSISTENT: true
  SHUFFLE: true
  RATIO: [1, 1]
  USE_GPU: true
  BLUR: 0.5
PAI: false

MODEL:
  NAME: ContrastiveModel
VIDEO:
  HEAD:
    NAME: ContrastiveHead