_BASE_RUN: ../../pool/run/training/simclr.yaml
_BASE_MODEL: ../../pool/backbone/vit-s.yaml
PRETRAIN:
  NUM_CLIPS_PER_VIDEO: 2
  CONTRASTIVE:
    TEMPERATURE: 0.2
    WITH_ONE: true
    MODE: 1
    HEAD_BN: true
    FINAL_BN: false
    SIM_FUNC_POS: linear
    SIM_FUNC_NEG: linear
    POS_OPTIM_TARGET: 1.0
    HEAD_MID_DIM: 4096
    HEAD_OUT_DIM: 256
    INS_MIL: false

TRAIN:
  ENABLE: true
  DATASET: longvideo
  BATCH_SIZE: 24
  LOG_FILE: training_log.log
  EVAL_PERIOD: 0
  NUM_FOLDS: 10
  AUTO_RESUME: true
  CHECKPOINT_PERIOD: 10
  CHECKPOINT_FILE_PATH: ""          # !!@2
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_INFLATE: false
  FINE_TUNE: false
  ONLY_LINEAR: false
TEST:
  ENABLE: false
DATA:
  DATA_ROOT_DIR: /mnt/data/dataset/k400-full/clip_5s/
  ANNO_DIR: /mnt/data/dataset/k400-full/
OSS:
  ENABLE: false
VIDEO:
  BACKBONE:
    DROP_PATH: 0.

BN:
  SYNC_BN: true
HICO:
  GRAUDAL_SAMPLING:
    ENABLE: false
    MAX_DIS: [0.0, 1.0]
  VCL:
    ENABLE: false
    MAX_DIS: 1.0
  TCL:
    ENABLE: false

OPTIMIZER:
  BASE_LR: 0.0002
  LR_POLICY: cosine
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.1
  WARMUP_EPOCHS: 5
  WARMUP_START_LR: 0.000002
  OPTIM_METHOD: adamw
  DAMPENING: 0.0
  NESTEROV: true
  BN_LARS_EXCLUDE: true
  ADJUST_LR: true
DATA_LOADER:
  NUM_WORKERS: 4
PAI: true

