_BASE: ../hico++_uk400_s3dg.yaml
OUTPUT_DIR: output/s3dg-uk400-hico++m6/

TRAIN:
  BATCH_SIZE: 32 # V100 32G

PRETRAIN:
  NUM_CLIPS_PER_VIDEO: 4
  LOSS: HiCoPlusPlus

VIDEO:
  HEAD:
    NAME: ContrastiveHeadTopicPredPlusPlus

DATA:
  DECORD_RESOLUTION_SCALE: 1.0
  HICO_PLUS_PLUS: 
    ENABLE: true

HICO:
  GRAUDAL_SAMPLING:
    ENABLE: true
    MAX_DIS: [0.0, 1.5]
  VCL:
    ENABLE: false
    MAX_DIS: 1.0
  TCL:
    ENABLE: true
  LOSS:
    GAMA: 0.5
    TCL_WEIGHT: 1.0
    VCL_WEIGHT: 1.0

OPTIMIZER:
  BN_LARS_EXCLUDE: true
  MAX_EPOCH: 50
  MIN_LR_RATE: 0.0

AUGMENTATION:
  USE_GPU: false

OSS:
  ENABLE: false
